---
- name: Provision an EC2 node
  hosts: 127.0.0.1
  connection: local
  gather_facts: False

  vars:
    report_file: "{{ lookup('ansible.builtin.env', 'AWS_PROFILE') }}_unused_ebs_report.csv"

  tasks:
    - amazon.aws.ec2_vol_info:
      register: vol_info

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: "{{report_file}}"
        state: absent

    - name: Touch the same file
      ansible.builtin.file:
        path: "{{report_file}}"
        state: touch

    - name: "Display volumes with available status with Jinja"
      copy:
        content: |
          {% for item in vol_info.volumes %}
            {% if item.status == 'available' %}
              {% if item.tags.Name is defined %}
                {{item.id}},{{item.zone}},{{item.tags.Name}}
              {% else %}
                {{item.id}},{{item.zone}},"No Name"
              {% endif %}
            {% endif %}
          {% endfor %}
        dest: "{{report_file}}"

    - name: Remove empty lines from  file
      lineinfile:
        path: "{{report_file}}"
        state: absent
        regexp: '^\s*$'

    - name: Remove trailing spaces
      command: sed -it 's/^ *//' "{{report_file}}"

#    - meta: end_play

#    - name: "Display volumes with available status"
#      lineinfile:
#        line: |
#          {% if item.tags.Name is defined %}
#            {{item.id}},{{item.zone}},{{item.tags.Name}}
#          {% else %}
#            {{item.id}},{{item.zone}},"No Name"
#          {% endif %}
#        dest: "{{aws_account}}_report.csv"
#        insertafter: EOF
#      when: item.status == 'available'
#      with_items: "{{vol_info.volumes}}"
